apiVersion: v1
kind: Pod
metadata: 
  name: meme-app
  labels:
    app: k8s-memes
spec:
  containers:
  - name: k8s-meme-app
    image: pavangudiwada/buildxtest2:latest
    ports:
      - containerPort: 5000
        protocol: TCP
    resources:
      limits:
        memory: "128Mi"